# Generated by Django 5.1.7 on 2025-03-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, verbose_name='название мероприятия')),
                ('img', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Картинка')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('published', models.DateField(auto_now_add=True, db_index=True, verbose_name='Опубликовано')),
                ('vote', models.IntegerField(blank=True, default=0, null=True)),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'мероприятие',
                'verbose_name_plural': 'Мероприятия',
                'ordering': ['-published'],
            },
        ),
    ]
