# Generated by Django 5.2.1 on 2025-05-30 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_events_date_events_location_alter_events_vote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AddField(
            model_name='events',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, related_name='joined_events', to=settings.AUTH_USER_MODEL, verbose_name='Участники'),
        ),
    ]
