# Generated by Django 5.2.1 on 2025-05-30 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_events_creator_events_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Опубликовано модератором'),
        ),
    ]
